version: "3"

services:
  #--------------------------------------------------
  frontend: # サービス名は変数は使えない
    container_name: ${CONTAINER_FRONT}_${APPNAME}_${PNAME}
    build:
      context: ../ # ビルド時のセルフディレクトリ
      dockerfile: ./.devcontainer/${CONTAINER_FRONT}/Dockerfile
      args: # ビルド時に使用する変数
        CONTAINER_FRONT: ${CONTAINER_FRONT}
        LOCALUID: ${LOCALUID}
        LOCALUNAME: ${LOCALUNAME}
        LOCALGID: ${LOCALGID}
        LOCALGNAME: ${LOCALGNAME}
        APPNAME: ${APPNAME}
    volumes:
      - ../${APPNAME}/${CONTAINER_FRONT}:/${CONTAINER_FRONT}
    environment: # コンテナ内に引き継ぐ変数
      CONTAINER_FRONT: ${CONTAINER_FRONT}
      NGATE: ${NGATE}
      PORT_BACK: ${PORT_BACK}
      CONTAINER_BACK: ${CONTAINER_BACK}
      CODESPACES: ${CODESPACES} # Codespace用
      CODESPACE_NAME: ${CODESPACE_NAME} # Codespace用
      GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN: ${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN} # Codespace用
      GITHUB_TOKEN: ${GITHUB_TOKEN} # Codespace用
    entrypoint: entrypoint.sh
    command: >  # PID1問題
      dumb-init /bin/sh
    tty: true
    ports:
      - ${PORT_FRONT}
    networks:
      - nw
    # secrets:
    #   - npmrc

  #--------------------------------------------------
  # backend: # サービス名は変数は使えない
  #   container_name: ${CONTAINER2}_${APPNAME}_${PNAME}
  #   build:
  #     context: .
  #     dockerfile: ./${CONTAINER2}/Dockerfile
  #     args: # Dockerfileに引き継ぐ変数
  #       CONTAINER2: ${CONTAINER2}
  #       LOCALUID: ${LOCALUID}
  #       LOCALUNAME: ${LOCALUNAME}
  #       LOCALGID: ${LOCALGID}
  #       LOCALGNAME: ${LOCALGNAME}
  #       APP_PATH: /${APPNAME}
  #   volumes:
  #     # - type: bind
  #     #   source: ./${CONTAINER2}
  #     #   target: /${APPNAME}:rw
  #     - ../${APPNAME}/${CONTAINER2}:/${APPNAME}:rw
  #   environment: # コンテナ内に引き継ぐ変数
  #     TZ: ${TZ}
  #     LANG: ${LANG}
  #     RAILS_ENV: development
  #     DB_NAME: ${DB_NAME}
  #     DB_USER: ${DB_USER}
  #     DB_PW: ${DB_PW}
  #     NGATE: ${NGATE}
  #     PORT1: ${PORT1}
  #     CODESPACE_NAME: ${CODESPACE_NAME} # Codespace用
  #     # MYPORT: ${PORT2} # Codespace用
  #     # CODESPACES: ${CODESPACES} # Codespace用
  #     # GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN: ${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN} # Codespace用
  #     # GITHUB_TOKEN: ${GITHUB_TOKEN} # Codespace用
  #   # command:
  #   command: /bin/sh
  #   ports:
  #     - ${PORT2}
  #   depends_on:
  #     - ${CONTAINER3}
  #   tty: true # 追記
  #   networks:
  #     - nw
  # #--------------------------------------------------
# RDB(cockroach)
# STRAGE(minio)
# REDIS()
# WEB(nginx)


  # https://qiita.com/taki_21/items/18a6c86f365545b940f3
  # rdb: # サービス名は変数は使えない
  #   image: minio/minio:latest
  #   container_name: ${CONTAINER3}_${APPNAME}_${PNAME}
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001" # コンソール用のポートフォワード設定
  #   environment:
  #     - TZ=${TZ}
  #     - PGTZ=${TZ}
  #     - MINIO_ROOT_USER=${DB_USER}
  #     - MINIO_ROOT_PASSWORD=${DB_PW}
  #   entrypoint: sh
  #   command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
  #   volumes:
  #     - ../${APPNAME}/${CONTAINER3}/data:/export
  #   networks:
  #     - nw
  # web:
  #   image: nginx:alpine
  #   ports:
  #     - 8888:80
  #   privileged: true
  #   volumes:
  #     - "./:/usr/share/nginx/html"
      
# http://ajisaba.net/develop/docker/docker-compose_ip.html
networks:
  nw:
    ipam:
      driver: default
      config:
        - subnet: ${NSUBW}
          gateway: ${NGATE}
# secrets:
#   npmrc:
#     file: ./${CONTAINER_FRONT}/.npmrc