# name: ${PNAME}
version: "3"

services:
  frontend: # サービス名は変数は使えない
    container_name: ${CONTAINER1}_${APPNAME}_${PNAME}
    build:
      context: .
      dockerfile: ./${CONTAINER1}/Dockerfile
      args:
        LOCALUID: ${LOCALUID}
        LOCALUNAME: ${LOCALUNAME}
        LOCALGID: ${LOCALGID}
        LOCALGNAME: ${LOCALGNAME}
        APP_PATH: /${APPNAME}
        CONTAINER1: ${CONTAINER1}
    volumes:
      - ../${APPNAME}/${CONTAINER1}:/${APPNAME}
    # command: yarn dev #OK
    # command: dumb-init yarn run #OK
    # command: dumb-init node /root/container.js #NG
    # https://qiita.com/bricolageart/items/a509594a5b4c349e90b7
    command: /bin/sh
    tty: true
    ports:
      - ${PORT1}
    networks:
      - nw

  backend: # サービス名は変数は使えない
    container_name: ${CONTAINER2}_${APPNAME}_${PNAME}
    build:
      context: .
      dockerfile: ./${CONTAINER2}/Dockerfile
      args: # Dockerfileに引き継ぐ変数
        LOCALUID: ${LOCALUID}
        LOCALUNAME: ${LOCALUNAME}
        LOCALGID: ${LOCALGID}
        LOCALGNAME: ${LOCALGNAME}
        APP_PATH: /${APPNAME}
        TZ: ${TZ}
        LANG: ${LANG}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PW: ${DB_PW}
        CONTAINER2: ${CONTAINER2}
    volumes:
      # - type: bind
      #   source: ./${CONTAINER2}
      #   target: /${APPNAME}:rw
      - ../${APPNAME}/${CONTAINER2}:/${APPNAME}:rw
    environment: # コンテナ内に引き継ぐ変数
      TZ: ${TZ}
      RAILS_ENV: development
    # command: rails server -e
    command: /bin/sh
    ports:
      - ${PORT2}
    depends_on:
      - ${CONTAINER3}
    tty: true # 追記
    networks:
      - nw

  db: # サービス名は変数は使えない
    image: postgres:14.3-alpine
    container_name: ${CONTAINER3}_${APPNAME}_${PNAME}
    environment:
      - TZ=${TZ}
      - PGTZ=${TZ}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
    volumes:
      # - type: bind
      #   source: ./${CONTAINER3}/data
      #   target: /var/lib/postgresql/data 
      - ../${APPNAME}/${CONTAINER3}/data:/var/lib/postgresql/data:rw
      # memo:https://nishinatoshiharu.com/docker-volume-tutorial/
    ports:
      - ${PORT3}

  adminer: # サービス名は変数は使えない
    image: adminer:latest
    container_name: ${CONTAINER4}_${APPNAME}_${PNAME}
    ports:
      - ${PORT4}
    # restart: always
    depends_on:
      - ${CONTAINER3}
    environment:
      - ADMINER_NAME="ADMINER for PostgreSQL DB"
      - ADMINER_SERVER="db"
      - ADMINER_DRIVER="pgsql"
      - ADMINER_DB=${DB_NAME}
      - ADMINER_USERNAME=${DB_USER}
      - ADMINER_PASSWORD=${DB_PW}

networks:
  nw:
    ipam:
      driver: default
      config:
        - gateway: 172.21.0.1